name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # 또는 배포하려는 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.17.0'  # 프로젝트에 맞는 Node.js 버전

    - name: Install dependencies
      run: npm install

    - name: Zip the code
      run: zip -r function.zip .

    - name: Deploy to Lambda
      uses: appleboy/lambda-action@v0.0.6
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: 'us-east-1'  # 해당되는 AWS 리전
        function_name: 'launchTime'  # Lambda 함수 이름
        zip_file: 'function.zip'
